services:
  you-education-backend-init-postgres-migration:
    image: you-education-backend:latest
    container_name: you-education-backend-init-postgres-migration
    command: sh -c "poetry run alembic upgrade head"
    volumes:
      - ./backend:/app
    networks:
      - personal_prod

  you-education-backend-init-mongodb-migration:
    image: you-education-backend:latest
    container_name: you-education-backend-init-mongodb-migration
    command: python -m init.mongodb_migrations
    volumes:
      - ./backend:/app
    networks:
      - personal_prod

  you-education-backend-init-milvus-migration:
    image: you-education-backend:latest
    container_name: you-education-backend-init-milvus-migration
    command: python -m init.milvus_migrations
    volumes:
      - ./backend:/app
    networks:
      - personal_prod

  you-education-backend:
    image: you-education-backend:latest
    container_name: you-education-backend
    command: uvicorn app.main:app --log-level debug --host 0.0.0.0 --port 80
    volumes:
      - ./backend:/app
    depends_on:
      you-education-backend-init-postgres-migration:
        condition: service_completed_successfully
      you-education-backend-init-mongodb-migration:
        condition: service_completed_successfully
      you-education-backend-init-milvus-migration:
        condition: service_completed_successfully
    labels:
      - traefik.enable=true
      - traefik.http.routers.you-education-backend.rule=Host(`you-education.devasheeshmishra.com`) && PathPrefix(`/api`)
      - traefik.http.routers.you-education-backend.entrypoints=personal
      - traefik.http.services.you-education-backend.loadbalancer.server.port=80
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - personal_prod

networks:
  personal_prod:
    external: true
