"""references and chunks

Revision ID: 1200d6417644
Revises: a079509a3c2b
Create Date: 2025-04-18 01:17:46.833869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1200d6417644'
down_revision: Union[str, None] = 'a079509a3c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.Enum('TXT', 'PDF', 'PPT', 'DOCX', 'MD', 'YT_VIDEO_URL', 'WEBSITE_URL', name='referencestypeenum'), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_type', 'file_name', 'exam_id', name='unique_reference_file_per_exam')
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('chunk_number', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id', 'chunk_number', name='unique_chunk_number_per_reference')
    )
    op.alter_column('exams', 'total_hours_to_dedicate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'total_hours_to_dedicate',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_table('chunks')
    op.drop_table('references')
    # ### end Alembic commands ###
